export function sanitizeName(value,fallback='file'){return String(value).normalize('NFKC').replace(/[<>:"/\\|?*\x00-\x1f]/g,'-').replace(/\.{2,}/g,'.').replace(/^[. ]+|[. ]+$/g,'').slice(0,100)||fallback;}
export function sanitizeFolder(value){const parts=String(value).replace(/\\/g,'/').split('/');if(!parts.length||parts.some(p=>!p||p==='.'||p==='..'))throw Error('Use a relative folder such as Invoices/2026.');return parts.map(p=>sanitizeName(p)).join('/');}
export function validateRule(input){const kind=['extension','domain','contains'].includes(input.kind)?input.kind:null;if(!kind)throw Error('Choose a valid rule type.');const value=String(input.value||'').trim().toLowerCase();if(!value||value.length>120)throw Error('Enter a matching value (up to 120 characters).');if(kind==='extension'&&!/^[a-z0-9]{1,12}$/.test(value.replace(/^\./,'')))throw Error('Use a file extension such as pdf.');if(kind==='domain'&&!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(value))throw Error('Use a domain such as example.com, without https://.');return{id:input.id||crypto.randomUUID(),kind,value:kind==='extension'?value.replace(/^\./,''):value,folder:sanitizeFolder(input.folder),enabled:input.enabled!==false,prefix:!!input.prefix};}
export function applyRules(item,rules,date=new Date()){const filename=String(item.filename||'download').split(/[\\/]/).pop();let host='';try{host=new URL(item.url).hostname.toLowerCase();}catch{}const ext=filename.includes('.')?filename.split('.').pop().toLowerCase():'';for(const r of rules){if(!r.enabled)continue;const matches=r.kind==='extension'?ext===r.value:r.kind==='domain'?(host===r.value||host.endsWith('.'+r.value)):filename.toLowerCase().includes(r.value);if(matches){const folder=sanitizeFolder(r.folder);const prefix=r.prefix?date.toISOString().slice(0,10)+'_':'';return folder+'/'+prefix+sanitizeName(filename);}}return null;}
export function parsePaise(value){const s=String(value).trim();if(!/^\d{1,8}(\.\d{1,2})?$/.test(s))throw Error('Enter an amount from 0 to 99,999,999.99 with at most 2 decimals.');const [a,b='']=s.split('.');return Number(a)*100+Number(b.padEnd(2,'0'));}
export const formatMoney=paise=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(paise/100);
const crcTable=Array.from({length:256},(_,i)=>{for(let n=0;n<8;n++)i=i&1?0xedb88320^(i>>>1):i>>>1;return i>>>0;});
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
export async function zipFiles(files){const chunks=[],central=[];let offset=0,centralSize=0;for(const file of files){const name=new TextEncoder().encode(file.name),data=new Uint8Array(await file.blob.arrayBuffer()),crc=crc32(data);const header=new Uint8Array(30+name.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);header.set(name,30);chunks.push(header,data);const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,crc,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);centralSize+=c.length;offset+=header.length+data.length;}const end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});}
