export const products = [
{"id":"revisiondesk","name":"RevisionDesk","tag":"TURN EXTRA WORK INTO AN AGREED PRICE","price":2499,"period":"annual","color":"#12533e","pale":"#e3f1e8","icon":"receipt","title":"One more change.\nOne clear proposal.","description":"Capture client requests, track agreed revision rounds and issue itemised proposals with recorded client responses.","features":["Browser capture with screenshot redaction","Scope allowances and explainable estimates","Immutable proposals and client response links"],"permission":"Active tab, scripting, context menus and storage. Captures only when you click. You choose whether to upload a screenshot.","limit":"Pro: 20 active projects, 100 requests per project and 50 proposals/month. Review links expire after 30 days. Site access restrictions apply. Responses are self-reported, not verified signatures.","free":"1 active project, 10 requests and 3 proposals/month","format":"Chrome extension + hosted workspace"},
{id:'filefit',name:'FileFit',tag:'FILES, READY TO GO',price:29,color:'#2764e7',pale:'#eaf0ff',icon:'file',title:'Make it fit.\nSend it off.',description:'Resize, convert and compress images for your next upload. All in one place.',features:['JPG, PNG & WebP conversion','Target size with a quality preview','Batch export as a ZIP'],permission:'Storage only. Processes the files you select.',limit:'Up to 20 images, 20 MB each. No PDF compression.',free:'3 export sessions per day',format:'Chrome extension + web app'},
{id:'claimpack',name:'ClaimPack',tag:'RECEIPTS, SORTED',price:49,color:'#9a4118',pale:'#fff0e5',icon:'receipt',title:'From receipt pile\nto reimbursement.',description:'Collect receipts, add your expenses and export one tidy claim document.',features:['Combine images and PDF receipts','Expense summary with INR totals','Reorder receipts before exporting'],permission:'Storage only. Processes the receipts you select.',limit:'Up to 20 receipts, 10 MB each, 50 MB total. Amounts are entered manually.',free:'3 claim exports per day',format:'Chrome extension + web app'},
{id:'sharesafe',name:'ShareSafe',tag:'SCREENSHOTS, WITH CARE',price:49,color:'#167356',pale:'#e5f5ec',icon:'shield',title:'Share the point.\nKeep the private bits.',description:'Crop, annotate and cover sensitive details before sharing a screenshot.',features:['Visible-tab capture in the extension','Permanent solid redaction on export','Arrows, crop, undo & PNG download'],permission:'Active tab on click and storage. No browsing-history access.',limit:'Visible-page capture only. Redaction is manual; review every export.',free:'3 image exports per day',format:'Chrome extension + image editor'},
{id:'downloadrules',name:'DownloadRules',tag:'DOWNLOADS, IN ORDER',price:49,color:'#6950b6',pale:'#f0ebfc',icon:'folder',title:'Less looking.\nMore finding.',description:'Give new downloads a home with simple filename, website and file-type rules.',features:['Sort into Downloads subfolders','Preview rules before enabling them','Rule priority & settings backup'],permission:'Downloads and storage. Applies only to new browser downloads.',limit:'Cannot move existing files or write outside Downloads. Chrome rules apply.',free:'2 active rules',format:'Chrome extension'}
,{"id":"stepguide","name":"StepGuide","tag":"TURN CLICKS INTO GUIDES","price":1499,"period":"annual","color":"#185b91","pale":"#e6f2ff","icon":"file","title":"Show it once.\nShare every step.","description":"Record a browser workflow and turn it into an editable, branded how-to guide.","features":["Click recording with visible screenshots","Edit, reorder and permanently redact steps","Branded PDF, HTML and editable backups"],"permission":"Active tab, tab list, scripting and storage. Optional access to the website you choose to record.","limit":"Desktop browser recording on one website at a time; up to 40 steps and 8 MB per guide. No desktop-app recording. Review screenshots before sharing.","free":"3 guide exports per day","format":"Chrome extension + guide editor"},
{"id":"replyready","name":"ReplyReady","tag":"YOUR BEST REPLIES, REUSED","price":799,"period":"annual","color":"#9a441f","pale":"#fff0e7","icon":"receipt","title":"Less retyping.\nMore personal.","description":"Personalise reusable replies, calculate quotations and expand shortcuts on selected websites.","features":["Templates with personalisation fields","Quantity × price quotation calculator","Site-specific shortcuts and JSON backups"],"permission":"Tab list, scripting and storage. Optional website access for shortcuts only.","limit":"Pro: up to 200 templates. Shortcuts support ordinary text inputs and textareas; use Copy for Gmail and rich editors. No auto-send or AI generation.","free":"5 templates with all composer features","format":"Chrome extension + reply composer"},
{"id":"watchdesk","name":"WatchDesk","tag":"KNOW WHEN THE PAGE CHANGES","price":999,"period":"annual","color":"#6b4db1","pale":"#f0eafd","icon":"shield","title":"Keep an eye on\nwhat matters.","description":"Watch a selected price, stock message or page section and review confirmed changes.","features":["Visual page-area picker or CSS selector","Local scheduled checks and browser alerts","Two-check confirmation and change history"],"permission":"Tabs, scripting, alarms, notifications and storage. Optional access to each monitored website.","limit":"Pro: 20 monitors; minimum 15-minute interval. Chrome must be running and the computer awake. Checks open a background tab. No cloud, email or SMS alerts.","free":"2 local monitors","format":"Chrome extension + text-comparison preview"},
{"id":"followupdesk","name":"FollowUp Desk","tag":"KEEP THE CONVERSATION MOVING","price":1499,"period":"annual","color":"#16715f","pale":"#e3f5ee","icon":"folder","title":"A follow-up.\nAt the right time.","description":"Keep Gmail conversations, reminders and follow-up drafts together on your device.","features":["Track button inside opened Gmail threads","Due reminders and thread-activity flags","Editable drafts, status tracking and backup"],"permission":"Scripting, alarms, notifications and storage. Optional access limited to Gmail.","limit":"Pro: 200 saved conversations. Reminders require Chrome running. Activity is detected only on opened Gmail threads and needs manual review; no automatic reply verification or sending.","free":"5 active reminders","format":"Chrome extension + manual tracker"}
];
export const getProduct=id=>products.find(p=>p.id===id);
export const paths={file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z M14 2v6h6 M8 13h8 M8 17h5',receipt:'M4 3l2 2 2-2 2 2 2-2 2 2 2-2 2 2 2-2v19l-2-2-2 2-2-2-2 2-2-2-2 2-2-2-2 2z M8 9h8 M8 13h8 M8 17h4',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6',folder:'M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M3 10h18'};
export const icon=(name,size=24)=>'<svg width="'+size+'" height="'+size+'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(paths[name]||paths.file)+'"/></svg>';
export const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
