
import {$,status,download,isExtension,read,write,act,rpc,webTabs,grantTab,jsonDownload,jsonFile,note} from '../shared/work.js';
import {escapeHtml as esc} from '../shared/catalog.js';import {exportGuard} from '../shared/ui.js';
export async function mount(root){
let guide=await read('guide')||{title:'My process guide',brand:'',color:'#244e34',steps:[]},recording=await read('recording');
root.innerHTML=note(isExtension?'First click the StepGuide toolbar icon on the website you want to record. Record that tab only. Only clicks on controls are recorded; input values are not collected. Screenshots may contain private information—review and redact before sharing.':'Web editor: add screenshots and instructions below. Install StepGuide to record browser actions.')+
'<section class="panel stack"><div class="row"><h2>Your guide</h2><span id="record-state" role="status"></span></div>'+(isExtension?'<div class="fields"><label>Website tab<select id="source-tab"></select></label><div class="row"><button class="btn secondary" id="refresh-tabs">Refresh tabs</button><button class="btn" id="record">Start recording</button><button class="btn secondary" id="stop">Stop recording</button></div></div>':'')+
'<div id="guide-edit"><div class="fields"><label>Guide title<input id="guide-title" maxlength="180"></label><label>Company or author<input id="guide-brand" maxlength="100"></label><label>Brand colour<input id="guide-color" type="color"></label><label>Logo (PNG/JPG, max 300 KB)<input type="file" id="guide-logo" accept="image/png,image/jpeg"></label></div><button id="remove-logo" class="btn secondary">Remove logo</button><label>Add screenshots (PNG/JPG/WebP, max 2 MB each)<input type="file" id="add-images" accept="image/png,image/jpeg,image/webp" multiple></label><div class="row"><button id="add-step" class="btn secondary">Add text step</button><button id="export-pdf" class="btn">Export PDF</button><button id="export-html" class="btn secondary">Export HTML</button><button id="backup-guide" class="btn secondary">Save editable backup</button></div><label>Restore a guide backup<input id="restore-guide" type="file" accept=".json,application/json"></label><p class="muted">Up to 40 steps. Redaction permanently replaces the saved image. PDF text is rendered as images; HTML exports retain selectable text.</p><div id="guide-steps" class="stack"></div></div></section>';
const save=async()=>{if(JSON.stringify(guide).length>8500000)throw Error('Guide exceeds the storage limit. Use fewer or smaller images.');if(isExtension)await rpc('save-guide',{guide});else await write('guide',guide);};
function header(){ $('#guide-title').value=guide.title;$('#guide-brand').value=guide.brand||'';$('#guide-color').value=guide.color||'#244e34';$('#record-state').textContent=recording?'Recording • '+guide.steps.length+' steps':'Ready • '+guide.steps.length+' steps';$('#guide-edit').hidden=!!recording;if(isExtension){$('#record').disabled=!!recording;$('#stop').disabled=!recording;}}
function render(){header();const list=$('#guide-steps');list.replaceChildren();guide.steps.forEach((step,index)=>{const card=document.createElement('article');card.className='guide-step';card.innerHTML='<div class="row"><h3>Step '+(index+1)+'</h3><button class="btn secondary up" '+(index===0?'disabled':'')+'>Move up</button><button class="btn secondary down" '+(index===guide.steps.length-1?'disabled':'')+'>Move down</button><button class="btn danger remove">Remove step</button></div><label>Instruction<textarea rows="2" maxlength="2000">'+esc(step.text)+'</textarea></label>'+(step.image?'<img class="guide-image" alt="Screenshot for step '+(index+1)+'" src="'+step.image+'"><details><summary>Cover sensitive information</summary><p class="muted">Coordinates are percentages of the screenshot. The rectangle is solid and cannot be undone.</p><div class="fields"><label>Left %<input class="left" type="number" min="0" max="99" value="0"></label><label>Top %<input class="top" type="number" min="0" max="99" value="0"></label><label>Width %<input class="width" type="number" min="1" max="100" value="20"></label><label>Height %<input class="height" type="number" min="1" max="100" value="10"></label></div><button class="btn danger redact">Apply permanent cover</button></details>':'<p class="muted">Text-only step. A screenshot may not have been available at capture time.</p>');$('textarea',card).onchange=act(async e=>{step.text=e.target.value;await save();});$('.up',card).onclick=act(async()=>{[guide.steps[index-1],guide.steps[index]]=[step,guide.steps[index-1]];await save();render();});$('.down',card).onclick=act(async()=>{[guide.steps[index+1],guide.steps[index]]=[step,guide.steps[index+1]];await save();render();});$('.remove',card).onclick=act(async()=>{guide.steps.splice(index,1);await save();render();});if(step.image)$('.redact',card).onclick=act(async()=>{const values=['left','top','width','height'].map(c=>Number($('.'+c,card).value));const[x,y,w,h]=values;if(values.some(n=>!Number.isFinite(n))||x<0||y<0||w<=0||h<=0||x+w>100||y+h>100)throw Error('Keep the cover rectangle within 0–100%.');const img=await loadImage(step.image);const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);ctx.fillStyle='#000';ctx.fillRect(Math.floor(x*canvas.width/100),Math.floor(y*canvas.height/100),Math.ceil(w*canvas.width/100),Math.ceil(h*canvas.height/100));step.image=canvas.toDataURL('image/png');await save();render();status('Sensitive area permanently covered. Review the full image before export.');});list.append(card);});}
for(const [id,key]of [['guide-title','title'],['guide-brand','brand'],['guide-color','color']])$('#'+id).onchange=act(async e=>{guide[key]=e.target.value;await save();});
$('#guide-logo').onchange=act(async e=>{const f=e.target.files[0];if(!f||f.size>300000||!['image/png','image/jpeg'].includes(f.type))throw Error('Choose a PNG or JPG logo under 300 KB.');guide.logo=await dataURL(f);await save();status('Logo saved. It will appear in exports.');});
$('#remove-logo').onclick=act(async()=>{delete guide.logo;await save();status('Logo removed.');});
$('#add-step').onclick=act(async()=>{if(guide.steps.length>=40)throw Error('Maximum 40 steps.');guide.steps.push({id:crypto.randomUUID(),text:'Describe this step',image:''});await save();render();});
$('#add-images').onchange=act(async e=>{const files=[...e.target.files];if(guide.steps.length+files.length>40)throw Error('Maximum 40 steps.');const additions=[];for(const f of files){if(f.size>2000000||!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('Choose supported images under 2 MB each.');const source=await dataURL(f);await loadImage(source);additions.push({id:crypto.randomUUID(),text:f.name,image:source});}const updated={...guide,steps:[...guide.steps,...additions]};if(JSON.stringify(updated).length>8500000)throw Error('Guide is too large. Choose fewer images.');guide=updated;await save();render();e.target.value='';});
$('#backup-guide').onclick=()=>jsonDownload({format:'astra-guide-1',guide},'stepguide-backup.json');
$('#restore-guide').onchange=act(async e=>{const data=await jsonFile(e.target.files[0],9000000),g=data.guide;if(data.format!=='astra-guide-1'||!g||typeof g.title!=='string'||!Array.isArray(g.steps)||g.steps.length>40)throw Error('Invalid StepGuide backup.');for(const s of g.steps){if(typeof s.text!=='string'||s.text.length>2000||s.image&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s.image))throw Error('Invalid step in backup.');if(s.image)await loadImage(s.image);}if(g.logo&&!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(g.logo))throw Error('Invalid logo.');g.color=/^#[0-9a-f]{6}$/i.test(g.color)?g.color:'#244e34';g.brand=String(g.brand||'').slice(0,100);guide=g;await save();render();status('Guide restored.');});
const exportReady=()=>{if(!guide.steps.length)throw Error('Add a step first.');};
$('#export-html').onclick=act(async()=>{exportReady();await exportGuard('stepguide',async()=>{const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(guide.title)+'</title><style>body{font:18px/1.6 system-ui;max-width:850px;margin:40px auto;padding:24px;color:#19382a}h1{color:'+guide.color+'}section{margin:35px 0;break-inside:avoid}img{max-width:100%}.logo{max-height:70px}p{white-space:pre-wrap}</style>'+(guide.logo?'<img class="logo" alt="Company logo" src="'+guide.logo+'">':'')+'<p>'+esc(guide.brand)+'</p><h1>'+esc(guide.title)+'</h1>'+guide.steps.map((s,i)=>'<section><h2>Step '+(i+1)+'</h2><p>'+esc(s.text)+'</p>'+(s.image?'<img alt="Screenshot for step '+(i+1)+'" src="'+s.image+'">':'')+'</section>').join('')+'</html>';download(new Blob([html],{type:'text/html'}),'stepguide.html');});});
$('#export-pdf').onclick=act(async()=>{exportReady();await exportGuard('stepguide',async()=>{const b=$('#export-pdf');b.disabled=true;try{status('Preparing your PDF…');await pdfLibrary();const doc=await PDFLib.PDFDocument.create();for(let i=0;i<guide.steps.length;i++){const step=guide.steps[i],canvas=document.createElement('canvas');canvas.width=1240;canvas.height=1754;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,1240,1754);ctx.fillStyle=guide.color;ctx.fillRect(0,0,1240,14);let y=65;if(guide.logo){const logo=await loadImage(guide.logo),scale=Math.min(180/logo.naturalWidth,70/logo.naturalHeight);ctx.drawImage(logo,60,y,logo.naturalWidth*scale,logo.naturalHeight*scale);y+=90;}ctx.fillStyle='#244e34';ctx.font='24px system-ui';y=wrap(ctx,guide.brand||'StepGuide',60,y,1120,34);ctx.font='bold 34px system-ui';y=wrap(ctx,guide.title,60,y+30,1120,45);ctx.font='bold 26px system-ui';ctx.fillText('Step '+(i+1),60,y+35);ctx.font='26px system-ui';y=wrap(ctx,step.text,60,y+85,1120,37);if(y>1300)throw Error('Step '+(i+1)+' has too much text for a page. Split it into more steps.');if(step.image){const img=await loadImage(step.image),scale=Math.min(1120/img.naturalWidth,(1620-y)/img.naturalHeight);ctx.drawImage(img,60,y+20,img.naturalWidth*scale,img.naturalHeight*scale);}ctx.font='20px system-ui';ctx.fillText((i+1)+' / '+guide.steps.length,60,1700);const image=await doc.embedJpg(canvas.toDataURL('image/jpeg',.9));const page=doc.addPage([620,877]);page.drawImage(image,{x:0,y:0,width:620,height:877});}download(new Blob([await doc.save()],{type:'application/pdf'}),'stepguide.pdf');status('Guide exported.');}finally{b.disabled=false;}});});
if(isExtension){await webTabs($('#source-tab'));const source=await read('step-source');if(source)$('#source-tab').value=String(source);$('#refresh-tabs').onclick=act(()=>webTabs($('#source-tab')));$('#record').onclick=act(async()=>{const tab=await grantTab($('#source-tab'));await save();await rpc('start',{tabId:tab.id});recording={tabId:tab.id};render();});$('#stop').onclick=act(async()=>{await rpc('stop');recording=null;guide=await read('guide')||guide;render();});chrome.storage.onChanged.addListener(async(changes,area)=>{if(area!=='local')return;if(changes.recording){recording=changes.recording.newValue;guide=await read('guide')||guide;render();}else if(changes.guide&&recording){guide=changes.guide.newValue;header();}});}
render();}
function dataURL(f){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Unable to read image.'));r.readAsDataURL(f);});}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>i.naturalWidth*i.naturalHeight>24000000?reject(Error('Image exceeds 24 megapixels.')):resolve(i);i.onerror=()=>reject(Error('Invalid image.'));i.src=src;});}
function wrap(ctx,text,x,y,width,line){let row='';for(const char of String(text)){if(char==='\n'||ctx.measureText(row+char).width>width){ctx.fillText(row,x,y);y+=line;row='';if(char==='\n')continue;}row+=char;}ctx.fillText(row,x,y);return y+line;}
async function pdfLibrary(){if(globalThis.PDFLib)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL('../vendor/pdf-lib.min.js',import.meta.url).href;s.onload=resolve;s.onerror=()=>reject(Error('PDF library could not load.'));document.head.append(s);});}
