
import {route,saved,save,openTool,owner,serial,notify} from './runtime.js';
import {gmailUrl,threadKey,dueReminder} from './shared/pro.js';import {isPro} from './shared/license.js';
const lock=serial();chrome.action.onClicked.addListener(()=>openTool('followupdesk'));
async function setup(){await chrome.alarms.create('followup-tick',{periodInMinutes:1});}
chrome.runtime.onInstalled.addListener(setup);chrome.runtime.onStartup.addListener(setup);
route((m,s)=>lock(async()=>{if(['track-current','activity'].includes(m.type)){if(!s.tab||!s.url?.startsWith('https://mail.google.com/')||!await chrome.permissions.contains({origins:['https://mail.google.com/*']}))throw Error('Open Gmail to track a conversation.');const url=gmailUrl(s.url),key=threadKey(url);if(!key)return;if(m.type==='track-current'){await save('follow-selection',{url,title:String(m.title).slice(0,180),fingerprint:String(m.fingerprint||'').slice(0,4000)});await openTool('followupdesk');return;}const rows=await saved('followups',[]);let changed=false;for(const row of rows){if(threadKey(row.url)!==key||row.status!=='waiting')continue;const next=String(m.fingerprint||'').slice(0,4000);if(!next)continue;if(row.fingerprint&&next!==row.fingerprint){row.activity=true;row.activityAt=new Date().toISOString();}row.fingerprint=next;changed=true;}if(changed)await save('followups',rows);return;}owner(s);await setup();if(m.type==='connect'){await chrome.scripting.unregisterContentScripts({ids:['astra-gmail']}).catch(()=>{});await chrome.scripting.registerContentScripts([{id:'astra-gmail',matches:['https://mail.google.com/*'],js:['content.js'],runAt:'document_idle'}]);for(const tab of await chrome.tabs.query({url:'https://mail.google.com/*'}))await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content.js']}).catch(()=>{});return;}
if(m.type==='disconnect'){await chrome.scripting.unregisterContentScripts({ids:['astra-gmail']}).catch(()=>{});await chrome.permissions.remove({origins:['https://mail.google.com/*']});return;}
if(m.type==='save'){if(!Array.isArray(m.rows)||m.rows.length>200)throw Error('Maximum 200 conversations.');if(!await isPro('followupdesk')&&m.rows.filter(x=>x.status==='waiting').length>5)throw Error('Free version includes 5 active reminders.');for(const row of m.rows){gmailUrl(row.url);if(!threadKey(row.url))throw Error('Use the address of a specific Gmail conversation.');if(!['waiting','replied','done'].includes(row.status)||!Number.isFinite(Date.parse(row.due)))throw Error('Choose a valid status and reminder date.');if(JSON.stringify(row).length>18000)throw Error('Conversation notes are too long.');}return save('followups',m.rows);}throw Error('Unknown action.');}));
chrome.alarms.onAlarm.addListener(a=>{if(a.name==='followup-tick')return lock(async()=>{const rows=await saved('followups',[]);let count=0;const max=await isPro('followupdesk')?200:5;for(const row of rows){if(row.status==='waiting'&&++count>max)continue;if(dueReminder(row)){await notify('follow-'+row.id,'FollowUp Desk reminder',row.title+' is due for a follow-up.');row.notified=true;}}await save('followups',rows);});});
chrome.notifications.onClicked.addListener(id=>{if(id.startsWith('follow-'))openTool('followupdesk');});
