import {$,status,download} from '../shared/ui.js';import {read,write,isExtension,isPro} from '../shared/license.js';import {validateRule,applyRules} from '../shared/core.js';import {escapeHtml} from '../shared/catalog.js';
export async function mount(root){root.innerHTML=(!isExtension?'<p class="tool-shell-note">Rule preview only. Install DownloadRules to organise new browser downloads. Settings here stay in this browser.</p>':'')+'<div class="tool-grid"><section class="panel"><h2>Your download rules</h2><p class="muted">First matching enabled rule wins. Files are never overwritten: Chrome adds a suffix if a name already exists.</p><div id="rule-list"></div><div class="row" style="margin-top:22px"><button id="backup" class="btn secondary">Export settings</button><label class="btn secondary" style="margin:0">Import settings<input id="import" type="file" accept="application/json" style="max-width:200px"></label></div></section><section class="panel"><h2>Add a rule</h2><form id="rule-form"><label>Match by<select id="rule-kind"><option value="extension">File extension</option><option value="domain">Download website</option><option value="contains">Filename contains</option></select></label><label>Matching value<input id="rule-value" required maxlength="120" placeholder="pdf"></label><label>Folder inside Downloads<input id="rule-folder" required maxlength="180" placeholder="Documents/Invoices"></label><label class="rule-enabled"><input type="checkbox" id="rule-prefix"> Prefix the filename with today’s date</label><button type="submit" class="btn" style="margin-top:15px">Add rule</button></form><p class="muted" style="margin-top:18px">Try: pdf → Documents, or invoices.example.com → Invoices. Website rules use the final download URL.</p></section></div><section class="panel" style="margin-top:24px"><h2>Test before you download</h2><div class="fields"><label>Example filename<input id="test-file" value="invoice-september.pdf"></label><label>Example download URL<input id="test-url" type="url" value="https://example.com/invoice-september.pdf"></label></div><button id="test" class="btn secondary">Preview destination</button><div class="preview-result" id="preview-result">Add a rule, then test a filename.</div></section>';
let rules=[];try{const saved=await read('rules');if(Array.isArray(saved))rules=saved.slice(0,100).map(validateRule);}catch{status('Saved rules could not be read. Import a valid settings backup to restore them.',true);}const pro=await isPro('downloadrules');
async function persist(){await write('rules',rules);render();}
function render(){$('#rule-list').innerHTML=rules.length?rules.map((r,i)=>'<article class="rule-card" data-id="'+r.id+'"><div class="row"><label class="rule-enabled"><input type="checkbox" data-action="toggle" '+(r.enabled?'checked':'')+' aria-label="Enable rule '+(i+1)+'"><strong>'+escapeHtml(r.value)+' → '+escapeHtml(r.folder)+'</strong></label><div class="row"><button class="btn secondary" data-action="up" aria-label="Move rule '+(i+1)+' up" '+(i===0?'disabled':'')+'>↑</button><button class="btn secondary" data-action="down" aria-label="Move rule '+(i+1)+' down" '+(i===rules.length-1?'disabled':'')+'>↓</button><button class="btn danger" data-action="remove" aria-label="Remove rule '+(i+1)+'">×</button></div></div><small>Match: '+escapeHtml(r.kind)+(r.prefix?' · Date prefix':'')+'</small></article>').join(''):'<p class="muted" style="padding:25px 0">No rules yet. Add your first rule to give new downloads a home.</p>';}
render();$('#rule-form').onsubmit=async e=>{e.preventDefault();try{if(rules.length>=100)throw Error('Maximum 100 rules.');if(!pro&&rules.filter(r=>r.enabled).length>=2)throw Error('The free version supports 2 active rules. Disable one or activate a licence.');const r=validateRule({kind:$('#rule-kind').value,value:$('#rule-value').value,folder:$('#rule-folder').value,prefix:$('#rule-prefix').checked});rules.push(r);await persist();$('#rule-form').reset();status('Rule added'+(isExtension?'. It applies to future matching downloads.':' to the preview.'));}catch(e){status(e.message,true);}};
$('#rule-list').addEventListener('change',async e=>{if(e.target.dataset.action!=='toggle')return;const rule=rules.find(r=>r.id===e.target.closest('[data-id]').dataset.id);if(e.target.checked&&!pro&&rules.filter(r=>r.enabled).length>=2){e.target.checked=false;status('Activate a licence for more than 2 active rules.',true);return;}rule.enabled=e.target.checked;try{await persist();}catch(err){status(err.message,true);}});
$('#rule-list').addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const i=rules.findIndex(r=>r.id===b.closest('[data-id]').dataset.id);if(b.dataset.action==='remove')rules.splice(i,1);else{const j=i+(b.dataset.action==='up'?-1:1);if(j>=0&&j<rules.length)[rules[i],rules[j]]=[rules[j],rules[i]];}try{await persist();}catch(err){status(err.message,true);}});
$('#test').onclick=()=>{try{new URL($('#test-url').value);const name=applyRules({filename:$('#test-file').value,url:$('#test-url').value},rules);$('#preview-result').textContent=name?'Downloads/'+name:'No rule matches. Chrome’s normal download behaviour is used.';}catch(e){status('Use a valid URL and folder: '+e.message,true);}};
$('#backup').onclick=()=>download(new Blob([JSON.stringify({version:1,rules},null,2)],{type:'application/json'}),'downloadrules-settings.json');
$('#import').onchange=async()=>{const file=$('#import').files[0];if(!file)return;try{if(file.size>200000)throw Error('Settings file is too large.');const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.rules)||data.rules.length>100)throw Error('Choose a version 1 DownloadRules settings file.');const imported=data.rules.map(r=>validateRule({...r,id:crypto.randomUUID()}));if(!pro&&imported.filter(r=>r.enabled).length>2)throw Error('This backup has more than 2 active rules. Activate a licence first.');rules=imported;await persist();status('Settings imported.');}catch(e){status(e.message,true);}$('#import').value='';};
}
