import fs from 'node:fs';import path from 'node:path';import {products} from '../public/shared/catalog.js';import {STORE_ORIGIN} from '../public/shared/config.js';import {zipFiles} from '../public/shared/core.js';
const root=fs.realpathSync(process.cwd());
function target(relative){const resolved=path.resolve(root,relative);if(!resolved.startsWith(root+path.sep))throw Error('Output must stay inside the project.');return resolved;}
function write(file,text){fs.mkdirSync(path.dirname(target(file)),{recursive:true});fs.writeFileSync(target(file),text);}
function copy(from,to){fs.mkdirSync(path.dirname(target(to)),{recursive:true});fs.copyFileSync(target(from),target(to));}
if(!fs.existsSync(target('public/shared/config.js')))throw Error('Run scripts/setup-keys.mjs first.');
for(const p of products){const base='extensions/'+p.id;fs.mkdirSync(target(base),{recursive:true});const workPermissions={stepguide:['activeTab','tabs','scripting','storage'],replyready:['tabs','scripting','storage'],watchdesk:['tabs','scripting','alarms','notifications','storage'],followupdesk:['scripting','alarms','notifications','storage']};const permissions=p.id==='revisiondesk'?['activeTab','scripting','storage','contextMenus']:workPermissions[p.id]|| (p.id==='sharesafe'?['activeTab','storage']:p.id==='downloadrules'?['downloads','storage']:['storage']);const icons=Object.fromEntries([16,32,48,128].map(size=>[size,'icons/icon-'+size+'.png']));
write(base+'/manifest.json',JSON.stringify({manifest_version:3,name:p.name+' — Astra Tools',version:'1.1.0',description:p.description,minimum_chrome_version:p.id==='revisiondesk'?'123':'116',permissions,...(p.id==='revisiondesk'?{externally_connectable:{matches:[STORE_ORIGIN+'/*']}}:{}),...(workPermissions[p.id]?{optional_host_permissions:p.id==='followupdesk'?['https://mail.google.com/*']:['https://*/*','http://*/*']} : {}),icons,action:{default_title:'Open '+p.name,default_icon:icons},background:{service_worker:'background.js',type:'module'},options_page:'tool.html?tool='+p.id,content_security_policy:{extension_pages:"script-src 'self'; object-src 'none'"}},null,2));
let html=fs.readFileSync(target('public/tool.html'),'utf8').replace('<html lang="en">','<html lang="en" data-tool="'+p.id+'">');write(base+'/tool.html',html);copy('public/tools.css',base+'/tools.css');copy('public/favicon.svg',base+'/favicon.svg');for(const f of fs.readdirSync(target('public/shared')))copy('public/shared/'+f,base+'/shared/'+f);copy('public/tools/boot.js',base+'/tools/boot.js');copy('public/tools/'+p.id+'.js',base+'/tools/'+p.id+'.js');for(const size of [16,32,48,128])copy('public/icons/'+p.id+'-'+size+'.png',base+'/icons/icon-'+size+'.png');
if(['claimpack','stepguide'].includes(p.id))for(const f of fs.readdirSync(target('public/vendor')))copy('public/vendor/'+f,base+'/vendor/'+f);
let background="chrome.action.onClicked.addListener(() => chrome.tabs.create({url:chrome.runtime.getURL('tool.html?tool="+p.id+"')}));\n";
if(p.id==='sharesafe')background="chrome.action.onClicked.addListener(async tab => { const id=crypto.randomUUID(); let data; try { if(!/^https?:/.test(tab.url||'')) throw Error('This browser page cannot be captured. Open a regular website or choose an image in the editor.'); const url=await chrome.tabs.captureVisibleTab(tab.windowId,{format:'png'}); data={url}; } catch(error) { data={error:error.message}; } await chrome.storage.session.set({['capture:'+id]:data}); await chrome.tabs.create({url:chrome.runtime.getURL('tool.html?tool=sharesafe&capture='+id)}); });\n";
if(p.id==='downloadrules')background+="import {applyRules,validateRule} from './shared/core.js';\nimport {isPro} from './shared/license.js';\nchrome.downloads.onDeterminingFilename.addListener((item,suggest)=>{ (async()=>{ try {const saved=(await chrome.storage.local.get('rules')).rules; let rules=Array.isArray(saved)?saved.slice(0,100).map(validateRule):[]; if(!await isPro('downloadrules'))rules=rules.filter(r=>r.enabled).slice(0,2); const filename=applyRules({filename:item.filename,url:item.finalUrl||item.url},rules); if(filename)suggest({filename,conflictAction:'uniquify'});else suggest(); } catch { suggest(); } })(); return true; });\n";
if(p.id==='revisiondesk')background=fs.readFileSync(target('extension-src/revisiondesk.js'),'utf8');
if(workPermissions[p.id]){background=fs.readFileSync(target('extension-src/'+p.id+'.js'),'utf8');copy('extension-src/'+p.id+'-content.js',base+'/content.js');copy('extension-src/runtime.js',base+'/runtime.js');}
write(base+'/background.js',background);write(base+'/README.txt',p.name+' — Astra Tools v1.1.0\n\nExtract this ZIP. Open chrome://extensions, enable Developer mode, click Load unpacked and choose this folder. Pin the extension to open it.\n\n'+p.permission+'\n'+p.limit+'\nFree: '+p.free+'. Activate a purchased licence inside the workspace.\n');
const entries=[];function walk(dir,prefix=''){for(const entry of fs.readdirSync(target(dir),{withFileTypes:true})){const file=dir+'/'+entry.name,name=prefix+entry.name;if(entry.isDirectory())walk(file,name+'/');else entries.push({name,blob:new Blob([fs.readFileSync(target(file))])});}}walk(base);write('public/downloads/'+p.id+'.zip',Buffer.from(await(await zipFiles(entries)).arrayBuffer()));}
const bundle=[];for(const p of products){const base=target('extensions/'+p.id);function collect(dir,prefix){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())collect(f,prefix+e.name+'/');else bundle.push({name:prefix+e.name,blob:new Blob([fs.readFileSync(f)])});}}collect(base,p.id+'/');}const install='Astra Tools — nine extension previews\n\nExtract this ZIP. At chrome://extensions enable Developer mode, then Load unpacked and select an individual product folder. Repeat for the tools you want.\n\nDetailed instructions: https://astra-tools.villanpotter.chatgpt.site/install.html\n\nKeep Chrome running for WatchDesk checks and FollowUp Desk reminders. These are developer previews, not Chrome Web Store listings. Checkout remains disabled until merchant configuration and testing.\n';bundle.push({name:'INSTALL.txt',blob:new Blob([install])});const allZip=Buffer.from(await(await zipFiles(bundle)).arrayBuffer());write('public/downloads/astra-all.zip',allZip);write('releases.local/Astra-Tools-Extensions.zip',allZip);write('releases.local/INSTALL.md',install);
fs.mkdirSync(target('dist/client'),{recursive:true});fs.cpSync(target('public'),target('dist/client'),{recursive:true});copy('public/shared/catalog.js','dist/server/catalog.js');write('dist/server/index.js',fs.readFileSync(target('server/index.js'),'utf8').replace('../public/shared/catalog.js','./catalog.js'));copy('.openai/hosting.json','dist/.openai/hosting.json');write('dist/server/revision.js',fs.readFileSync(target('server/revision.js'),'utf8').replaceAll('../public/shared/','./shared/'));fs.cpSync(target('public/shared'),target('dist/server/shared'),{recursive:true});fs.cpSync(target('drizzle'),target('dist/.openai/drizzle'),{recursive:true});
console.log('Built storefront, Cloudflare Worker and nine Manifest V3 extension ZIPs.');
