
import {route,saved,save,openTool,owner,serial} from './runtime.js';
import {httpUrl} from './shared/pro.js';
const lock=serial();chrome.action.onClicked.addListener(async tab=>{await save('step-source',tab.id);await openTool('stepguide');});
async function stop(){await chrome.scripting.unregisterContentScripts({ids:['astra-steps']}).catch(()=>{});await save('recording',null);await chrome.action.setBadgeText({text:''});}
route((m,s)=>lock(async()=>{if(m.type==='step'){const rec=await saved('recording',null);if(!rec||s.tab?.id!==rec.tabId||httpUrl(s.url).origin!==rec.origin)return;const guide=await saved('guide',{title:'Untitled guide',steps:[]});if(guide.steps.length>=40){await stop();throw Error('40-step limit reached. Recording stopped.');}const step={id:crypto.randomUUID(),text:String(m.label||'Next step').slice(0,200),url:httpUrl(s.url).origin+new URL(s.url).pathname,at:new Date().toISOString(),image:''};const tab=await chrome.tabs.get(rec.tabId);if(tab.active){try{const image=await chrome.tabs.captureVisibleTab(tab.windowId,{format:'jpeg',quality:65});const active=await chrome.tabs.query({active:true,windowId:tab.windowId});if(active[0]?.id===rec.tabId)step.image=image;}catch{}}if(guide.steps.reduce((n,x)=>n+(x.image?.length||0),0)+step.image.length>6500000){await stop();throw Error('Guide storage limit reached. Export this guide before recording more.');}guide.steps.push(step);await save('guide',guide);await chrome.action.setBadgeText({text:String(guide.steps.length)});return;}
owner(s);if(m.type==='start'){if(m.tabId!==await saved('step-source',null))throw Error('First click the StepGuide toolbar icon on the website tab you want to record.');const tab=await chrome.tabs.get(m.tabId),url=httpUrl(tab.url);await stop();await chrome.scripting.registerContentScripts([{id:'astra-steps',matches:[url.origin+'/*'],js:['content.js'],runAt:'document_idle',persistAcrossSessions:false}]);await save('recording',{tabId:tab.id,origin:url.origin});await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content.js']});await chrome.tabs.update(tab.id,{active:true});await chrome.action.setBadgeText({text:'REC'});return;}
if(m.type==='stop')return stop();if(m.type==='save-guide'){if(!m.guide||!Array.isArray(m.guide.steps)||m.guide.steps.length>40||JSON.stringify(m.guide).length>8500000)throw Error('Guide is too large.');await stop();return save('guide',m.guide);}throw Error('Unknown action.');}));
chrome.tabs.onRemoved.addListener(async id=>{if((await saved('recording',null))?.tabId===id)await stop();});
chrome.runtime.onStartup.addListener(stop);
