
import {route,saved,save,openTool,owner,serial,notify} from './runtime.js';
import {httpUrl,monitorChange} from './shared/pro.js';import {isPro} from './shared/license.js';
const lock=serial();chrome.action.onClicked.addListener(()=>openTool('watchdesk'));
async function setup(){await chrome.alarms.create('watch-tick',{periodInMinutes:1});}
chrome.runtime.onInstalled.addListener(setup);chrome.runtime.onStartup.addListener(setup);
async function check(id){const rows=await saved('monitors',[]),i=rows.findIndex(x=>x.id===id);if(i<0)return;const item=rows[i];let tab;
try{if(!await isPro('watchdesk')&&i>=2)throw Error('Free version checks the first 2 monitors.');const origin=httpUrl(item.url).origin+'/*';if(!await chrome.permissions.contains({origins:[origin]}))throw Error('Website permission missing. Re-enable access in the workspace.');tab=await chrome.tabs.create({url:item.url,active:false});await new Promise((resolve,reject)=>{let done=false;const finish=(err)=>{if(done)return;done=true;clearTimeout(timer);chrome.tabs.onUpdated.removeListener(listener);err?reject(err):resolve();};const listener=(id,info)=>{if(id===tab.id&&info.status==='complete')finish();};const timer=setTimeout(()=>finish(Error('Page took too long to load.')),18000);chrome.tabs.onUpdated.addListener(listener);chrome.tabs.get(tab.id).then(t=>{if(t.status==='complete')finish();}).catch(finish);});await new Promise(r=>setTimeout(r,1500));const results=await chrome.scripting.executeScript({target:{tabId:tab.id},func:(selector)=>{const all=document.querySelectorAll(selector);if(all.length!==1)throw Error('Selector must match exactly one area.');const el=all[0];if(!el.getClientRects().length)throw Error('Selected area is hidden.');return(el.innerText||'').slice(0,12000);},args:[item.selector]});const result=monitorChange(item.baseline,results[0]?.result,item.pending);item.baseline=result.baseline;item.pending=result.pending;item.error='';if(result.changed){item.history=[{at:new Date().toISOString(),before:result.before,after:result.after},...(item.history||[])].slice(0,10);await notify('watch-'+id,'WatchDesk: change confirmed',item.name+' has changed. Open WatchDesk to review.');}}
catch(e){item.error=e.message||'Could not check this page.';}finally{if(tab?.id)await chrome.tabs.remove(tab.id).catch(()=>{});item.checked=new Date().toISOString();rows[i]=item;await save('monitors',rows);}return item;}
route((m,s)=>lock(async()=>{if(m.type==='picked'){if(!s.tab||!await chrome.permissions.contains({origins:[httpUrl(s.url).origin+'/*']})||httpUrl(s.url).origin!==httpUrl(m.url).origin)throw Error('Invalid selection.');await save('watch-selection',{url:s.url,selector:String(m.selector).slice(0,2000),text:String(m.text).slice(0,12000)});await openTool('watchdesk');return;}owner(s);await setup();if(m.type==='pick'){await chrome.scripting.executeScript({target:{tabId:m.tabId},files:['content.js']});await chrome.tabs.update(m.tabId,{active:true});return;}
if(m.type==='save'){if(!Array.isArray(m.rows)||m.rows.length>20)throw Error('Maximum 20 monitors.');if(!await isPro('watchdesk')&&m.rows.length>2)throw Error('Free version includes 2 monitors.');const previous=await saved('monitors',[]);const rows=m.rows.map(x=>{const u=httpUrl(x.url);if(typeof x.selector!=='string'||!x.selector||x.selector.length>2000)throw Error('Enter a valid CSS selector.');const old=previous.find(r=>r.id===x.id);return{...x,...(old?{baseline:old.baseline,pending:old.pending,history:old.history,checked:old.checked,error:old.error}:{}),url:u.href,name:String(x.name).slice(0,100),minutes:Math.max(15,Math.min(1440,Number(x.minutes)||60)),enabled:!!x.enabled};});return save('monitors',rows);}
if(m.type==='check')return check(m.id);throw Error('Unknown action.');}));
chrome.alarms.onAlarm.addListener(a=>{if(a.name==='watch-tick')return lock(async()=>{const rows=await saved('monitors',[]);const max=await isPro('watchdesk')?20:2;const next=rows.slice(0,max).find(x=>x.enabled&&(!x.checked||Date.now()-Date.parse(x.checked)>=x.minutes*60000));if(next)await check(next.id);});});
chrome.notifications.onClicked.addListener(id=>{if(id.startsWith('watch-'))openTool('watchdesk');});
