import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {handleApi,hmac,validatePayment} from '../server/index.js';import {verifyLicense} from '../public/shared/license.js';
const settings=JSON.parse(fs.readFileSync('.dev.vars','utf8'));const env={...settings,RAZORPAY_KEY_ID:'rzp_test_example',RAZORPAY_KEY_SECRET:'test-only-secret',CHECKOUT_ENABLED:'true'};
function provider(overrides={}){return async(url,init)=>{if(url.endsWith('/payments/pay_example'))return Response.json({order_id:'order_example',amount:2900,currency:'INR',status:'captured',captured:true,amount_refunded:0,...overrides});if(url.endsWith('/orders/order_example'))return Response.json({amount:2900,currency:'INR',notes:{store:'astra-tools',product:'filefit',major:'1',email:'buyer@example.com'}});if(url.endsWith('/orders')&&init.method==='POST'){const data=JSON.parse(init.body);assert.equal(data.amount,2900);return Response.json({id:'order_example',amount:data.amount,currency:data.currency});}return new Response('',{status:404});};}
const req=(path,data,origin='https://astra.test')=>new Request('https://astra.test'+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)});
test('unconfigured store cannot create orders',async()=>{assert.equal((await handleApi(req('/api/orders',{product:'filefit',email:'buyer@example.com'}),{})).status,503);});
test('order price is server-owned even if caller changes amount',async()=>{const res=await handleApi(req('/api/orders',{product:'filefit',email:'buyer@example.com',amount:1}),env,provider());assert.equal(res.status,200);assert.equal((await res.json()).amount,2900);});
test('cross-origin order requests are blocked',async()=>{assert.equal((await handleApi(req('/api/orders',{product:'filefit',email:'buyer@example.com'},'https://evil.test'),env,provider())).status,403);});
test('valid captured payment issues a product-specific signed licence',async()=>{const data=await validatePayment(env,'pay_example','buyer@example.com','order_example',provider());assert.ok(await verifyLicense(data.license,'filefit'));assert.equal(await verifyLicense(data.license,'sharesafe'),null);const parts=data.license.split('.');parts[0]=parts[0].slice(0,-2)+'AA';assert.equal(await verifyLicense(parts.join('.'),'filefit'),null);});
test('wrong email, wrong amount, refunded and uncaptured payments fail',async()=>{await assert.rejects(()=>validatePayment(env,'pay_example','other@example.com',null,provider()));for(const value of [{amount:1},{currency:'USD'},{status:'authorized',captured:false},{amount_refunded:100}])await assert.rejects(()=>validatePayment(env,'pay_example','buyer@example.com',null,provider(value)));});
test('checkout proof requires valid HMAC',async()=>{let res=await handleApi(req('/api/verify',{orderId:'order_example',paymentId:'pay_example',email:'buyer@example.com',signature:'invalid'}),env,provider());assert.equal(res.status,400);const signature=await hmac(env.RAZORPAY_KEY_SECRET,'order_example|pay_example');res=await handleApi(req('/api/verify',{orderId:'order_example',paymentId:'pay_example',email:'buyer@example.com',signature}),env,provider());assert.equal(res.status,200);});
