
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {fieldsIn,renderTemplate,quoteTotal,monitorChange,gmailUrl,threadKey,dueReminder,validSnippet} from '../public/shared/pro.js';
import {signLicense,validatePayment,handleApi} from '../server/index.js';import {verifyLicense} from '../public/shared/license.js';
const env={...JSON.parse(fs.readFileSync('.dev.vars','utf8')),RAZORPAY_KEY_ID:'rzp_test_example',RAZORPAY_KEY_SECRET:'test-only',CHECKOUT_ENABLED:'true'};
test('templates preserve literal replacement text and quotation rounds paise',()=>{assert.deepEqual(fieldsIn('{{name}} {{name}} {{total}}'),['name','total']);assert.equal(renderTemplate('Hi {{name}}',{name:'$& <img>'}),'Hi $& <img>');assert.equal(quoteTotal(3,0.1),'0.30');assert.throws(()=>quoteTotal(-1,9));assert.throws(()=>validSnippet({title:'x',body:'x',shortcut:'has space'}));});
test('monitor requires two identical changed observations; whitespace and blanks do not alert',()=>{assert.equal(monitorChange('Stock  2',' Stock 2 ').changed,false);let r=monitorChange('old','new');assert.equal(r.changed,false);r=monitorChange(r.baseline,'new',r.pending);assert.equal(r.changed,true);assert.equal(r.before,'old');assert.equal(monitorChange('old','different','new').changed,false);assert.throws(()=>monitorChange('old','   '));});
test('Gmail identity preserves account and ignores inbox/sent view; reminders are one-shot',()=>{const a='https://mail.google.com/mail/u/0/#inbox/1234567890abcdef';const b='https://mail.google.com/mail/u/0/#sent/1234567890abcdef';assert.equal(threadKey(a),threadKey(b));assert.notEqual(threadKey(a),threadKey(a.replace('/u/0/','/u/1/')));assert.equal(threadKey('https://mail.google.com/mail/u/0/#inbox'),'');assert.throws(()=>gmailUrl('https://mail.google.com.evil.test/mail/u/0/#inbox'));assert.equal(dueReminder({status:'waiting',due:'2020-01-01',notified:false}),true);assert.equal(dueReminder({status:'waiting',due:'2020-01-01',notified:true}),false);assert.equal(dueReminder({status:'replied',due:'2020-01-01'}),false);});
test('annual licences expire, are product-bound, and retain exact payment term on recovery',async()=>{const paidAt=Math.floor(Date.now()/1000)-60;const token=await signLicense(env,'stepguide','pay_example',paidAt);assert.equal((await verifyLicense(token,'stepguide')).expiresAt,paidAt+365*86400);assert.equal(await verifyLicense(token,'replyready'),null);const expired=await signLicense(env,'stepguide','pay_old',paidAt-366*86400);assert.equal(await verifyLicense(expired,'stepguide'),null);await assert.rejects(()=>signLicense(env,'stepguide','pay_missing'));const fetcher=async url=>Response.json(url.includes('/payments/')?{order_id:'order_example',amount:149900,currency:'INR',status:'captured',captured:true,created_at:paidAt}:{amount:149900,currency:'INR',notes:{store:'astra-tools',product:'stepguide',major:'1',email:'buyer@example.com',termDays:'365'}});const a=await validatePayment(env,'pay_example','buyer@example.com',null,fetcher),b=await validatePayment(env,'pay_example','buyer@example.com',null,fetcher);assert.equal(a.expiresAt,b.expiresAt);assert.equal((await verifyLicense(b.license,'stepguide')).expiresAt,paidAt+365*86400);});
test('annual orders carry server-owned price and 365-day term',async()=>{const req=new Request('https://astra.test/api/orders',{method:'POST',headers:{Origin:'https://astra.test','Content-Type':'application/json'},body:JSON.stringify({product:'replyready',email:'buyer@example.com',amount:1,termDays:9999})});const res=await handleApi(req,env,async(url,init)=>{const data=JSON.parse(init.body);assert.equal(data.amount,79900);assert.equal(data.notes.termDays,'365');return Response.json({id:'order_example',amount:data.amount,currency:'INR'});});assert.equal(res.status,200);});
