
import test from 'node:test';import assert from 'node:assert/strict';
function event(){const listeners=[];return {addListener:fn=>listeners.push(fn),removeListener:fn=>{const i=listeners.indexOf(fn);if(i>=0)listeners.splice(i,1);},emit:(...args)=>Promise.all(listeners.map(fn=>fn(...args))),listeners};}
function mock(){const state={},notifications=[],registered=new Map(),closed=[];let result='In stock',permission=true;
globalThis.chrome={runtime:{id:'test',getURL:p=>'chrome-extension://test/'+p,onMessage:event(),onInstalled:event(),onStartup:event()},storage:{local:{get:async k=>({[k]:structuredClone(state[k])}),set:async v=>{Object.assign(state,structuredClone(v));}},onChanged:event()},action:{onClicked:event(),setBadgeText:async()=>{}},tabs:{onRemoved:event(),onUpdated:event(),get:async id=>({id,url:'https://example.com/item',active:true,windowId:1,status:'complete'}),query:async()=>[{id:11,url:'https://example.com/item',active:true}],create:async()=>({id:21,windowId:1}),update:async()=>{},remove:async id=>closed.push(id),captureVisibleTab:async()=> 'data:image/jpeg;base64,AAAA'},scripting:{unregisterContentScripts:async({ids})=>ids.forEach(id=>registered.delete(id)),registerContentScripts:async rows=>rows.forEach(x=>registered.set(x.id,x)),getRegisteredContentScripts:async()=>[...registered.values()],executeScript:async()=>[{result}]},permissions:{contains:async()=>permission,remove:async()=>{permission=false;},getAll:async()=>({origins:['https://example.com/*']})},alarms:{create:async()=>{},onAlarm:event()},notifications:{create:async(id,data)=>notifications.push({id,...data}),onClicked:event()}};
const send=(type,data={},sender={id:'test',url:'chrome-extension://test/tool.html'})=>new Promise(resolve=>{chrome.runtime.onMessage.listeners[0]({type,...data},sender,resolve);});
return {state,send,registered,closed,notifications,result:value=>result=value,permission:value=>permission=value};}
test('StepGuide records only explicitly selected tab and rejects content-script control messages',async()=>{const m=mock();await import('../extensions/stepguide/background.js');await chrome.action.onClicked.emit({id:11});assert.equal((await m.send('start',{tabId:12})).ok,false);assert.equal((await m.send('start',{tabId:11})).ok,true);assert.equal(m.registered.size,1);await m.send('step',{label:'Select Save'},{id:'test',url:'https://example.com/item',tab:{id:12}});assert.equal(m.state.guide,undefined);await m.send('step',{label:'Select Save'},{id:'test',url:'https://example.com/item',tab:{id:11}});assert.equal(m.state.guide.steps.length,1);assert.ok(m.state.guide.steps[0].image.startsWith('data:image/'));assert.equal((await m.send('stop',{}, {id:'test',url:'https://example.com/item',tab:{id:11}})).ok,false);await m.send('stop');assert.equal(m.state.recording,null);await m.send('step',{label:'Should not record'},{id:'test',url:'https://example.com/item',tab:{id:11}});assert.equal(m.state.guide.steps.length,1);});
test('ReplyReady expands permitted snippets, enforces free list and respects revoked permissions',async()=>{const m=mock();await import('../extensions/replyready/background.js');m.state.snippets=Array.from({length:6},(_,i)=>({shortcut:'s'+i,body:'Hello {{name}}'}));m.state['reply-values']={name:'Asha'};const sender={id:'test',url:'https://example.com/form',tab:{id:11}};assert.equal((await m.send('expand',{shortcut:'s0'},sender)).data,'Hello Asha');assert.equal((await m.send('expand',{shortcut:'s5'},sender)).data,null);m.permission(false);assert.equal((await m.send('expand',{shortcut:'s0'},sender)).ok,false);assert.equal((await m.send('enable',{tabId:11,url:'https://example.com'},sender)).ok,false);});
test('WatchDesk establishes baseline, confirms a change twice and cleans temporary tabs on errors',async()=>{const m=mock();await import('../extensions/watchdesk/background.js');const item={id:'a',url:'https://example.com/item',name:'Stock',selector:'#stock',minutes:15,enabled:true};assert.equal((await m.send('save',{rows:[item]})).ok,true);await m.send('check',{id:'a'});assert.equal(m.state.monitors[0].baseline,'In stock');m.result('Sold out');await m.send('check',{id:'a'});assert.equal(m.notifications.length,0);await m.send('check',{id:'a'});assert.equal(m.notifications.length,1);assert.equal(m.state.monitors[0].history[0].before,'In stock');assert.equal(m.closed.length,3);m.result('');await m.send('check',{id:'a'});assert.match(m.state.monitors[0].error,/empty/);assert.equal(m.state.monitors[0].baseline,'Sold out');assert.equal(m.closed.length,4);assert.equal((await m.send('save',{rows:[item,{...item,id:'b'},{...item,id:'c'}]})).ok,false);});
test('FollowUp Desk emits one due reminder, flags observed activity and stops Gmail reads after disconnect',async()=>{const m=mock();await import('../extensions/followupdesk/background.js');const url='https://mail.google.com/mail/u/0/#inbox/1234567890abcdef';assert.equal((await m.send('save',{rows:[{id:'a',title:'Proposal',url,due:'2020-01-01',status:'waiting',fingerprint:'message1'}]})).ok,true);await chrome.alarms.onAlarm.emit({name:'followup-tick'});await chrome.alarms.onAlarm.emit({name:'followup-tick'});assert.equal(m.notifications.length,1);const sender={id:'test',url,tab:{id:11}};await m.send('activity',{fingerprint:'message1|message2'},sender);assert.equal(m.state.followups[0].activity,true);assert.equal(m.state.followups[0].status,'waiting');await m.send('disconnect');assert.equal((await m.send('activity',{fingerprint:'message3'},sender)).ok,false);});
