import {revisionApi} from './revision.js';
import {products} from '../public/shared/catalog.js';
const prices=Object.fromEntries(products.map(p=>[p.id,p.price*100]));
const encoder=new TextEncoder();
export const b64=bytes=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export function same(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
export async function hmac(secret,message){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(message)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function signLicense(env,product,paymentId,paidAt){const key=await crypto.subtle.importKey('jwk',JSON.parse(env.LICENSE_PRIVATE_JWK),{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const p=products.find(x=>x.id===product);const annual=p?.period==='annual';if(annual&&(!Number.isFinite(paidAt)||paidAt<=0||paidAt>Date.now()/1000+300))throw Error('Payment timestamp is invalid. Contact support.');const body=b64(encoder.encode(JSON.stringify({issuer:'astra-tools',product,major:1,paymentId,...(annual?{expiresAt:paidAt+365*86400}:{})})));const signature=b64(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,encoder.encode(body))));return body+'.'+signature;}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function configured(env){return !!(env.RAZORPAY_KEY_ID&&env.RAZORPAY_KEY_SECRET&&env.LICENSE_PRIVATE_JWK);}
function email(value){const e=String(value||'').trim().toLowerCase();if(e.length>180||!/^\S+@\S+\.\S+$/.test(e))throw Error('Enter a valid email address.');return e;}
export async function provider(env,path,method='GET',body,fetcher=fetch){const response=await fetcher('https://api.razorpay.com/v1/'+path,{method,headers:{Authorization:'Basic '+btoa(env.RAZORPAY_KEY_ID+':'+env.RAZORPAY_KEY_SECRET),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw Error('Payment service unavailable or payment not found. Please check the details and retry.');return response.json();}
export async function validatePayment(env,paymentId,buyerEmail,expectedOrder,fetcher=fetch){if(!/^pay_[A-Za-z0-9]{4,64}$/.test(paymentId))throw Error('Enter the payment ID from your receipt.');const payment=await provider(env,'payments/'+paymentId,'GET',null,fetcher);if(!payment.order_id||!/^order_[A-Za-z0-9]+$/.test(payment.order_id))throw Error('This payment does not belong to an Astra Tools order.');if(expectedOrder&&payment.order_id!==expectedOrder)throw Error('Payment and order do not match.');const order=await provider(env,'orders/'+payment.order_id,'GET',null,fetcher);const p=order.notes?.product;if(!prices[p]||order.notes?.store!=='astra-tools'||order.notes?.major!=='1'||!same(String(order.notes?.email||''),email(buyerEmail)))throw Error('No matching purchase found. Check your email and payment ID.');if(order.amount!==prices[p]||payment.amount!==prices[p]||order.currency!=='INR'||payment.currency!=='INR')throw Error('Payment amount does not match this product. Contact support.');if(payment.status!=='captured'||payment.captured!==true)throw Error('The payment is not captured yet. Please try recovery shortly; do not pay again.');if(Number(payment.amount_refunded||0)>0)throw Error('This payment has been refunded. Contact support if you need help.');const annual=products.find(x=>x.id===p)?.period==='annual';if(annual&&order.notes?.termDays!=='365')throw Error('Purchase term does not match this product.');return{product:p,paymentId,license:await signLicense(env,p,paymentId,payment.created_at),...(annual?{expiresAt:payment.created_at+365*86400}:{})};}
export async function handleApi(request,env,fetcher=fetch){const url=new URL(request.url);if(url.pathname==='/api/config'&&request.method==='GET')return json({checkoutEnabled:env.CHECKOUT_ENABLED==='true'&&configured(env),testMode:!!env.RAZORPAY_KEY_ID?.startsWith('rzp_test_')});if(request.method!=='POST')return json({error:'Method not allowed.'},405);if(request.headers.get('Origin')!==url.origin)return json({error:'Please use checkout on the Astra Tools website.'},403);if(!request.headers.get('Content-Type')?.includes('application/json'))return json({error:'JSON request required.'},415);if(Number(request.headers.get('Content-Length')||0)>12000)return json({error:'Request too large.'},413);let text='';if(request.body){const reader=request.body.getReader();const decoder=new TextDecoder();let bytes=0;while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.byteLength;if(bytes>12000){await reader.cancel();return json({error:'Request too large.'},413);}text+=decoder.decode(chunk.value,{stream:true});}text+=decoder.decode();}if(!configured(env))return json({error:'Purchases are not enabled yet. Try the free tools for now.'},503);let data;try{data=JSON.parse(text);}catch{return json({error:'Invalid request.'},400);}try{
if(url.pathname==='/api/orders'){if(env.CHECKOUT_ENABLED!=='true')return json({error:'Checkout is temporarily unavailable.'},503);const buyer=email(data.email);if(!Object.hasOwn(prices,data.product))return json({error:'Unknown product.'},400);const order=await provider(env,'orders','POST',{amount:prices[data.product],currency:'INR',receipt:'astra_'+crypto.randomUUID().replaceAll('-',''),notes:{store:'astra-tools',product:data.product,major:'1',email:buyer,...(products.find(p=>p.id===data.product)?.period==='annual'?{termDays:'365'}:{})}},fetcher);if(!/^order_[A-Za-z0-9]+$/.test(order.id)||order.amount!==prices[data.product]||order.currency!=='INR')throw Error('The payment provider returned an invalid order.');return json({orderId:order.id,keyId:env.RAZORPAY_KEY_ID,amount:prices[data.product]});}
if(url.pathname==='/api/verify'){if(!/^order_[A-Za-z0-9]{4,64}$/.test(data.orderId||'')||!/^pay_[A-Za-z0-9]{4,64}$/.test(data.paymentId||''))throw Error('Invalid payment details.');const expected=await hmac(env.RAZORPAY_KEY_SECRET,data.orderId+'|'+data.paymentId);if(!same(expected,data.signature))return json({error:'Payment signature verification failed.'},400);return json(await validatePayment(env,data.paymentId,data.email,data.orderId,fetcher));}
if(url.pathname==='/api/recover')return json(await validatePayment(env,String(data.paymentId||''),data.email,null,fetcher));
return json({error:'Not found.'},404);
}catch(e){return json({error:e.message||'Unable to complete the request.'},400);}}
export default {async fetch(request,env){const path=new URL(request.url).pathname;if(path==='/listmatch'||path==='/revisiondesk')return Response.redirect(new URL(path+'.html',request.url),308);if(path.startsWith('/api/revision/'))return revisionApi(request,env);if(path.startsWith('/api/'))return handleApi(request,env);if(!env.ASSETS)return new Response('Static assets are unavailable.',{status:503});const response=await env.ASSETS.fetch(request);const headers=new Headers(response.headers);headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','strict-origin-when-cross-origin');headers.set('X-Frame-Options','DENY');headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self' https://checkout.razorpay.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*.razorpay.com; font-src 'self'; connect-src 'self' https://*.razorpay.com; frame-src https://*.razorpay.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; worker-src 'self' blob:");return new Response(response.body,{status:response.status,headers});}};
